### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by liu-lihao** [egoist/esbuild-plugin-vue#4]
```js
import { createApp } from 'vue'
import Index from '/src/options/index.vue'

const app = createApp(Index)
app.mount('#root')
```

```js
 // The same is true for other onloads
 build.onLoad({filter: /\.vue$/, namespace: "vue"}, async (args) => {
     // args.path === '/src/options/index.vue'
    //  The original code will report an error
    //  no such file or directory, open '/src/options/index.vue'
    const content = await fs.promises.readFile(args.path, "utf8");
    // temporary solution
    const content = await fs.promises.readFile(path.join(process.cwd(), args.path), "utf8");
    // In fact, we should consider relative path, absolute path and alias,
    // but we can't get other information through args

    // ...
 }
```

**Comment by liu-lihao** [comment]
Sorry, I didn't notice that onResolve could handle path. I'll add pr

**Comment by egoist** [comment]
we can't assume that `/src` is the same as `$cwd/src`, because they're not, `/src` is an absolute path.

**Comment by liu-lihao** [comment]
Sorry, you're right. I've looked at the document about `absWorkingDir` again. I'll revise it here

**Comment by liu-lihao** [comment]
updated

**Comment by Akryum** [comment]
Have this issue with a simple relative import:

```js
import SomeComponent from './SomeComponent.vue'
```

I get:

```
> src/index.ts:2:26: error: [plugin: vue] ENOENT: no such file or directory, open './SomeComponent.vue'
     2 │ import SomeComponent from './SomeComponent.vue'
       ╵                           ~~~~~~~~~~~~~~~~~~~~~
   node_modules/esbuild-plugin-vue/dist/index.js:29:12: note: This error came from the "onLoad" callback registered here
    29 │       build.onLoad({filter: /\.vue$/, namespace: "vue"}, async (args) => {
       ╵             ~~~~~~
    at setup (/home/akryum/Projects/demos/vue-devtools-plugin/node_modules/esbuild-plugin-vue/dist/index.js:29:13)
    at handlePlugins (/home/akryum/Projects/demos/vue-devtools-plugin/node_modules/esbuild/lib/main.js:736:23)
    at Object.buildOrServe (/home/akryum/Projects/demos/vue-devtools-plugin/node_modules/esbuild/lib/main.js:1024:7)
    at /home/akryum/Projects/demos/vue-devtools-plugin/node_modules/esbuild/lib/main.js:1748:17
    at new Promise (<anonymous>)
    at Object.build (/home/akryum/Projects/demos/vue-devtools-plugin/node_modules/esbuild/lib/main.js:1747:14)
    at Object.build (/home/akryum/Projects/demos/vue-devtools-plugin/node_modules/esbuild/lib/main.js:1623:51)
    at Object.<anonymous> (/home/akryum/Projects/demos/vue-devtools-plugin/esbuild.js:22:9)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
```

**Comment by Akryum** [comment]
I can confirm https://github.com/egoist/esbuild-plugin-vue/pull/5 fixes the issue for me

**Comment by egoist** [comment]
Should work now with `v0.1.3`
